apiVersion: v1
kind: ConfigMap
metadata:
  name: vk-profile-config
data:
  application.properties: |
    spring.application.name=vk-profile-service
    server.port=8080
    
    # VK API Configuration
    vk.api.url=https://api.vk.com/method
    vk.api.version=5.131
    
    # Logging
    logging.level.root=INFO
    logging.level.com.vk.profileservice=INFO
    
    # Cache
    spring.cache.type=caffeine
    
    # Actuator
    management.endpoints.web.exposure.include=health,info,metrics,prometheus
    management.endpoint.health.show-details=always

